# Solving Systems of Linear Equations with NumPy - Lab

## Introduction 

Now you've gathered all the required skills needed to solve systems of linear equations. You saw why there was a need to calculate inverses of matrices, followed by matrix multiplication to figure out the values of unknown variables. 

The exercises in this lab present some problems that can be converted into a system of linear equations. 

## Objectives
You will be able to:

- Use matrix algebra and NumPy to solve a system of linear equations given a real-life example 
- Use NumPy's linear algebra solver to solve for systems of linear equations

## Exercise 1

A coffee shop is having a sale on coffee and tea. 

On day 1, 29 bags of coffee and 41 bags of tea were sold, for a total of 490 dollars.

On day 2, they sold 23 bags of coffee and 41 bags of tea, for which customers paid a total of 448 dollars.  

How much does each bag cost?

In [5]:
import numpy as np

# Create and solve the relevant system of equations
A = np.matrix([[29, 41],[23,41]])
B = np.matrix([490, 448])

A_inv = np.linalg.inv(A)
A_inv

B_T = B.T

X = A_inv.dot(B_T)
print(X)

[[7.]
 [7.]]


In [8]:
# Describe your result

# I assigned the values to A, the 'number of things' matrix, and the prices to the B matrix

# To solve, I invert the A and dot-multiply by the transposed B matrix

# Thus, both coffee and tea are $7 per bag

x = 7

print(29*x + 41*x == 490)
print(23*x + 41*x == 448)

True
True


## Exercise 2

The cost of admission to a popular music concert was 162 dollars for 12 children and 3 adults. 

The admission was 122 dollars for 8 children and 3 adults in the same music concert. 

How much was the admission for each child and adult?

In [10]:
from numpy.linalg import solve

In [14]:
# Create and solve the relevant system of equations

C = np.matrix([[12,3],[8,3]])
D = np.matrix([162,122])

solve(C,D.T)

matrix([[10.],
        [14.]])

In [15]:
# Describe your result

# This time I just used the numpy.linalg.solve() function, which still requires that I .T the price matrix
# This gives a result of ticket prices: $10 for kids, $14 for adults

x = 10
y = 14

print(12*x + 3*y == 162)
print(8*x + 3*y == 122)

True
True


## Exercise 3

You want to make a soup containing tomatoes, carrots, and onions.

Suppose you don't know the exact mix to put in, but you know there are 7 individual pieces of vegetables, and there are twice as many tomatoes as onions, and that the 7 pieces of vegetables cost 5.25 USD in total. 
You also know that onions cost 0.5 USD each, tomatoes cost 0.75 USD and carrots cost 1.25 USD each.

Create a system of equations to find out exactly how many of each of the vegetables are in your soup.

In [16]:
# Create and solve the relevant system of equations

# t, c, o are # of tomatoes/carrots/onions
# so the matrix needs three rows such that each when multiplied by the #'s, they equal:
# an amount row that equals 7
# prices that equals $5.25
# another that has twice as many tomatoes as onions, that equals 0

# 1,1,1
# .5, .75, 1.25
# 2, -1, 0

A = np.matrix([[1,1,1],[.5,.75,1.25],[2,-1,0]])
B = np.matrix([7, 5.25, 0])

A_inv = np.linalg.inv(A)
X = A_inv.dot(B.T)
print(X)

solve(A,B.T)

[[2.]
 [4.]
 [1.]]


matrix([[2.],
        [4.],
        [1.]])

In [18]:
# Describe your result

# Both the 'long' way and the .solve() way give us:
# 2 onions, 4 tomatoes, and 1 carrot

## Exercise 4

A landlord owns 3 properties: a 1-bedroom, a 2-bedroom, and a 3-bedroom house. 

The total rent he receives is 1240 USD. 

He needs to make some repairs, where those repairs cost 10% of the 1-bedroom house’s rent. The 2-bedroom repairs cost 20% of the 2-bedroom rental price and 30% of the 3-bedroom house's rent for its repairs.  The total repair bill for all three houses was 276 USD. 

The 3-bedroom house's rent is twice the 1-bedroom house’s rent. 

How much is the individual rent for three houses?

In [22]:
# Create and solve the relevant system of equations

# Similar approach as previous exercise

# 1/2/3 bedrooms = q/r/s

# .1q + .2r + .3s = 276
# q + r + s = 1240
# 2q + 0r + -s = 0

A = np.matrix([[1,1,1],[.1,.2,.3],[2,0,-1]])
B = np.matrix([1240,276,0])

A_inv = np.linalg.inv(A)
X = A_inv.dot(B.T)
print(X)

solve(A,B.T)

[[280.]
 [400.]
 [560.]]


matrix([[280.],
        [400.],
        [560.]])

In [21]:
# Describe your result

# 1/2/3 bedrooms prices = $280 / $400 / $560

## Summary
In this lab, you learned how to use NumPy to solve linear equations by taking inverses and matrix multiplication and also using numpy's `solve()` function. You'll now take these skills forward and see how you can define a simple regression problem using linear algebra and solve it with Numpy. 